### ISSUE TITLE
Suggestion: change the project name to something a little more distinctive?

### ISSUE THREAD

**Issue by edwinjhlee** [TimothyYe/knock-rs#3]
# English version translated by [gemini](https://x-cmd.com/mod/gemini)

Hello, knock author and community,
    
I recently started researching honeypots and SSH knocking projects, which led me to your project.
    
During my search, I noticed that this project shares the same name with https://github.com/jvinet/knock. It took me a while to confirm that jvinet/knock is the original, based on the author's name listed in the documentation:
    
    https://linux.die.net/man/1/knockd
    
I suggest choosing a more distinctive project name, at least slightly different (e.g., knockr or knocker). This would benefit promotion and community growth.
    
  ----------
    
Rewriting it in Rust is fantastic and could lead to more powerful features. Personally, I'm interested in a portable mode that doesn't require root privileges, allowing it to run on various systems and alongside other TCP services.
    
This might be a premature suggestion, but I hope it provides some food for thought.
    
I'm the developer of x-cmd, which enhances existing commands using shell scripts and offers a user-space portable package manager. I'm excited about the potential of knock to provide a more robust and portable solution.
    
For instance, our package manager offers a portable version of fastfetch: https://cn.x-cmd.com/pkg/fastfetch. 

# 中文原文

尊敬的knock 作者，社区，你好：

我最近开始调研 蜜罐 和 ssh 敲门相关的项目，然后发现这个项目。

在搜索的过程中，这个项目 与 https://github.com/jvinet/knock 同名，我花了一点时间才确定 jvinet/knock 才是正主，通过 这个资料：

https://linux.die.net/man/1/knockd 下面的 author 署名。

我建议取一个更有辨识度的项目名，至少有一点 diff （ 例如 knockr，或者 knocker ），这样更有利宣传和社区发展。

---

采用 rust 重写这个很棒，而且可能会增加更强大的功能 -- 我个人比较感兴趣的是可以成为一个 portable 而且不需要 root 的运行模式。并在不同的系统使用，与其它 tcp 服务使用。

我这个想法可能不太成熟，以供一贻。

我是 x-cmd 的开发者。x-cmd 一方面用 shell 来增强很多原有命令，另一方面自带一个 user space 的 portable pkg manager。所以我乐见 knock 能够为大家提供一个更强大的 portable 方案。

例如我们的 pkg 提供 portable 的 [fastfetch](https://cn.x-cmd.com/pkg/fastfetch) 。

**Comment by TimothyYe** [comment]
Renamed to `knock-rs`
